# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20170213_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dummy_field',
        ),
    ]
