# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20170214_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
