# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0005_auto_20170213_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='job_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
