# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20170213_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dummy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='dummy',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
