# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20170214_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dummy',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
