# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_category_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
