# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20170213_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('rejected', 'rejected'), ('selected', 'selected'), ('taken', 'taken'), ('closed', 'closed'), ('completed', 'completed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
