# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20170213_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('rejected', 'rejected'), ('selected', 'selected'), ('taken', 'taken'), ('closed', 'closed'), ('completed', 'completed')], default='open', max_length=10),
        ),
    ]
