# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dummy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
