# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(default='bangalore', max_length=100),
        ),
    ]
