# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0002_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('part_time', 'Part-time'), ('internship', 'Internship'), ('event', 'Event'), ('social_service', 'Social service')], default='part_time', max_length=10),
        ),
    ]
