# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0004_auto_20170218_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('taken', 'Taken'), ('closed', 'Closed'), ('completed', 'Completed'), ('applied', 'Applied')], default='open', max_length=10),
        ),
    ]
